import "./globals.css";
import { AppContextProvider } from "@/state/AppContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
