import './globals.css';
import { AppContextProvider } from '@/state/AppContext';
import DashboardLayout from '@/components/common/layout/Dashboard';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className=''>
				<AppContextProvider>
					{/* <DashboardLayout> */}
					{children}
					{/* </DashboardLayout> */}
				</AppContextProvider>
			</body>
		</html>
	);
}
