const historyTableData
= [
    {
        Symptoms: 'Oxygen deficiency, Dizziness, Fainting',
        treatment: 'Iron Deficiency',
        patient: 'Phoeebe',
        doctor: 'Doctor Peace',
        date: '11/11/23',
        prescription: 'Iron Tablet, fruits and vegetables, iron supp...',
        status: 'Active',
        testName: 'Blood-oxygen level',
        testMethod: 'Blood Sample',
        result: 'Oxygen deficiency',
        prescribedTo: 'Phoebe',
        prescribedby: 'Dr Peace',
        testDate: 'Dec 09, 23',
        drug: 'Iron supplement',
        doses: '50g',
        id: 121
    },
    {
        Symptoms: 'Oxygen deficiency, Dizziness, Fainting',
        treatment: 'Iron Deficiency',
        patient: 'Phoeebe',
        date: '11/11/23',
        prescription: 'Iron Tablet, fruits and vegetables, iron supp...',
        status: 'Active',
        testName: 'Blood-oxygen level',
        testMethod: 'Blood Sample',
        result: 'Oxygen deficiency',
        prescribedTo: 'Phoebe',
        testDate: 'Dec 09, 23',
        drug: 'Iron supplement',
        doses: '50g',
        doctor: 'Doctor Peace',
        prescribedby: 'Dr Peace',
        id: 122
    },
    {
        Symptoms: 'Oxygen deficiency, Dizziness, Fainting',
        treatment: 'Iron Deficiency',
        patient: 'Phoeebe',
        date: '11/11/23',
        prescription: 'Iron Tablet, fruits and vegetables, iron supp...',
        status: 'Done',
        testName: 'Blood-oxygen level',
        testMethod: 'Blood Sample',
        result: 'Oxygen deficiency',
        prescribedTo: 'Phoebe',
        testDate: 'Dec 09, 23',
        drug: 'Iron supplement',
        doses: '50g',
        doctor: 'Doctor Peace',
        prescribedby: 'Dr Peace',
        id: 123
    },
    {
        Symptoms: 'Oxygen deficiency, Dizziness, Fainting',
        treatment: 'Iron Deficiency',
        patient: 'Phoeebe',
        date: '11/11/23',
        prescription: 'Iron Tablet, fruits and vegetables, iron supp...',
        status: 'Done',
        testName: 'Blood-oxygen level',
        testMethod: 'Blood Sample',
        result: 'Oxygen deficiency',
        prescribedTo: 'Phoebe',
        testDate: 'Dec 09, 23',
        drug: 'Iron supplement',
        doses: '50g',
        doctor: 'Doctor Peace',
        prescribedby: 'Dr Peace',
        id: 124
    },
    {
        Symptoms: 'Oxygen deficiency, Dizziness, Fainting',
        treatment: 'Iron Deficiency',
        patient: 'Phoeebe',
        date: '11/11/23',
        prescription: 'Iron Tablet, fruits and vegetables, iron supp...',
        status: 'Done',
        testName: 'Blood-oxygen level',
        testMethod: 'Blood Sample',
        result: 'Oxygen deficiency',
        prescribedTo: 'Phoebe',
        testDate: 'Dec 09, 23',
        drug: 'Iron supplement',
        doses: '50g',
        doctor: 'Doctor Peace',
        prescribedby: 'Dr Peace',
        id: 125
    },
    {
        Symptoms: 'Oxygen deficiency, Dizziness, Fainting',
        treatment: 'Iron Deficiency',
        patient: 'Phoeebe',
        date: '11/11/23',
        prescription: 'Iron Tablet, fruits and vegetables, iron supp...',
        status: 'Done',
        testName: 'Blood-oxygen level',
        testMethod: 'Blood Sample',
        result: 'Oxygen deficiency',
        prescribedTo: 'Phoebe',
        testDate: 'Dec 09, 23',
        drug: 'Iron supplement',
        doses: '50g',
        doctor: 'Doctor Peace',
        prescribedby: 'Dr Peace',
        id: 126
    },
]

export default historyTableData
